name: Joe T. Sylve, Ph.D.
description: Digital Forensic Researcher and Educator
avatar: https://avatars.githubusercontent.com/u/594165

footer-links:
  email: joe.sylve@gmail.com
  github: jtsylve
  linkedin: jtsylve
  twitter: jtsylve
  mastodon: infosec.exchange/@jtsylve

google_analytics: G-MWNW1TK62B

url: https://jtsylve.blog
baseurl: ""

permalink: /post/:year/:month/:day/:title

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

paginate: 5
paginate_path: "/page/:num/"
